# Code generated by abstraction-idl from abstraction-identity/identity.thrift. DO NOT EDIT.

"""abstraction.identity.api: generated contract types, vocabularies and service clients."""

from ._codec import (
    NATIVE_BINDING_TYPES,
    NATIVE_OPERATIONS,
    Proof,
    ProofFailure,
    ProofRequirement,
    Refusal,
    decode,
    encode,
)

__all__ = [
    "NATIVE_BINDING_TYPES",
    "NATIVE_OPERATIONS",
    "Proof",
    "ProofFailure",
    "ProofRequirement",
    "Refusal",
    "decode",
    "encode",
]

# Report every class and function as a member of this package, so help(),
# tracebacks and pickles name the import an application writes.
for _name in __all__:
    _value = globals()[_name]
    if isinstance(_value, type) or callable(_value):
        _value.__module__ = __name__
del _name, _value
