// Code generated by abstraction-idl from abstraction-identity/identity.thrift. DO NOT EDIT.

#pragma once

#include <cstddef>
#include <cstdint>
#include <map>
#include <optional>
#include <stdexcept>
#include <string>
#include <string_view>
#include <vector>

namespace abstraction::identity::api {

using Raw = std::string;

class Refusal : public std::runtime_error {
public:
    Refusal(const char* word, std::size_t offset)
        : std::runtime_error(std::string("refused: ") + word + " at byte " + std::to_string(offset)),
          word(word),
          offset(offset) {}
    const char* word;
    std::size_t offset;
};

enum class Proof : std::int32_t {
    None = 1,
    Claimed = 2,
    Invalid = 3,
    Unsigned = 4,
    Unmet = 5,
    Pid = 6,
    Bound = 7,
    Kernel = 8,
    Signed = 9,
};

// The member's name on the wire; empty for a value that names no member.
inline constexpr std::string_view wire_name(Proof value) {
    switch (value) {
        case Proof::None: return "none";
        case Proof::Claimed: return "claimed";
        case Proof::Invalid: return "invalid";
        case Proof::Unsigned: return "unsigned";
        case Proof::Unmet: return "unmet";
        case Proof::Pid: return "pid";
        case Proof::Bound: return "bound";
        case Proof::Kernel: return "kernel";
        case Proof::Signed: return "signed";
    }
    return {};
}

// The member a wire name spells; empty for a name this vocabulary refuses.
inline std::optional<Proof> parse_proof(std::string_view name) {
    if (name == "none") return Proof::None;
    if (name == "claimed") return Proof::Claimed;
    if (name == "invalid") return Proof::Invalid;
    if (name == "unsigned") return Proof::Unsigned;
    if (name == "unmet") return Proof::Unmet;
    if (name == "pid") return Proof::Pid;
    if (name == "bound") return Proof::Bound;
    if (name == "kernel") return Proof::Kernel;
    if (name == "signed") return Proof::Signed;
    return std::nullopt;
}

// A member equals its wire name, so code holding the contract's word compares directly.
inline constexpr bool operator==(Proof value, std::string_view name) { return wire_name(value) == name; }
inline constexpr bool operator!=(Proof value, std::string_view name) { return wire_name(value) != name; }
inline constexpr bool operator==(std::string_view name, Proof value) { return wire_name(value) == name; }
inline constexpr bool operator!=(std::string_view name, Proof value) { return wire_name(value) != name; }

inline const std::vector<std::string> kProofNames = {"none", "claimed", "invalid", "unsigned", "unmet", "pid", "bound", "kernel", "signed"};

inline const std::vector<std::string> kNativeOperations = {"OfHandle", "OfConn", "CanEver", "Check", "Get", "AtLeast"};

inline const std::vector<std::string> kNativeBindingTypes = {"Handle", "Peer", "Attr<T>", "User", "Process", "Code", "Options"};

// Minimum proof for each native Peer attribute. Policy comparison uses the
// declared native order. A serialized requirement or proof name never supplies
// caller identity; native bindings derive values from the accepted connection.
struct ProofRequirement {
    Proof user{};
    Proof process{};
    Proof path{};
    Proof package{};
    Proof code{};
};

// Diagnostic refusal metadata. Underlying native attribute and connection
// evidence remain inseparable; this record cannot create authenticated
// evidence.
struct ProofFailure {
    std::string attribute;
    Proof have{};
    Proof need{};
    std::string why;
};

// Codec machinery. Nothing here is API; it may change in any release.
namespace detail {

inline void esc(std::string& out, const std::string& s);

inline void esc_byte(std::string& out, unsigned char c) {
    static const char* kHex = "0123456789abcdef";
    switch (c) {
        case '"': out += "\\\""; return;
        case '\\': out += "\\\\"; return;
        case 0x08: out += "\\b"; return;
        case 0x0c: out += "\\f"; return;
        case '\n': out += "\\n"; return;
        case '\r': out += "\\r"; return;
        case '\t': out += "\\t"; return;
        default: break;
    }
    if (c < 0x20) {
        out += "\\u00";
        out += kHex[c >> 4];
        out += kHex[c & 0x0F];
    } else {
        out += static_cast<char>(c);
    }
}

inline void num(std::string& out, std::int64_t n) { out += std::to_string(n); }

inline void pad(std::string& out, int depth) {
    out.append(static_cast<std::size_t>(depth) * 2, ' ');
}

inline void strs(std::string& out, const std::vector<std::string>& v, int depth) {
    if (v.empty()) { out += "[]"; return; }
    out += "[\n";
    for (std::size_t i = 0; i < v.size(); ++i) {
        pad(out, depth + 1);
        esc(out, v[i]);
        if (i + 1 < v.size()) out += ',';
        out += '\n';
    }
    pad(out, depth);
    out += ']';
}



inline bool ws(unsigned char c) { return c == ' ' || c == '\t' || c == '\n' || c == '\r'; }

inline void raw(std::string& out, const std::string& s, int depth) {
    const std::size_t n = s.size();
    for (std::size_t i = 0; i < n;) {
        const unsigned char c = static_cast<unsigned char>(s[i]);
        if (ws(c)) {
            ++i;
        } else if (c == '"') {
            std::size_t j = i + 1;
            while (j < n) {
                if (s[j] == '\\') { j += 2; continue; }
                if (s[j] == '"') { ++j; break; }
                ++j;
            }
            out.append(s, i, j - i);
            i = j;
        } else if (c == '{' || c == '[') {
            out += static_cast<char>(c);
            ++i;
            std::size_t j = i;
            while (j < n && ws(static_cast<unsigned char>(s[j]))) ++j;
            if (j < n && (s[j] == '}' || s[j] == ']')) {
                out += s[j];
                i = j + 1;
            } else {
                ++depth;
                out += '\n';
                pad(out, depth);
            }
        } else if (c == '}' || c == ']') {
            --depth;
            out += '\n';
            pad(out, depth);
            out += static_cast<char>(c);
            ++i;
        } else if (c == ',') {
            out += ",\n";
            pad(out, depth);
            ++i;
        } else if (c == ':') {
            out += ": ";
            ++i;
        } else {
            out += static_cast<char>(c);
            ++i;
        }
    }
}

// std::char_traits<char>::compare is specified to order by unsigned char, so a
// std::map<std::string, ...> already walks its keys in UTF-8 byte order — which
// is what the definition declares. Nothing sorts here because nothing needs to.
inline void rawmap(std::string& out, const std::map<std::string, Raw>& m, int depth) {
    if (m.empty()) { out += "{}"; return; }
    out += "{\n";
    std::size_t i = 0;
    for (const auto& kv : m) {
        pad(out, depth + 1);
        esc(out, kv.first);
        out += ": ";
        raw(out, kv.second, depth + 1);
        if (++i < m.size()) out += ',';
        out += '\n';
    }
    pad(out, depth);
    out += '}';
}

inline void esc(std::string& out, const std::string& s) {
    out += '"';
    for (unsigned char c : s) esc_byte(out, c);
    out += '"';
}
inline void enc_proof_requirement(std::string&, const ProofRequirement&, int);
inline void enc_proof_failure(std::string&, const ProofFailure&, int);

inline void enc_proof_requirement(std::string& out, const ProofRequirement& v, int depth) {
    if (wire_name(v.user).empty()) throw Refusal("bad_enum", 0);
    if (wire_name(v.process).empty()) throw Refusal("bad_enum", 0);
    if (wire_name(v.path).empty()) throw Refusal("bad_enum", 0);
    if (wire_name(v.package).empty()) throw Refusal("bad_enum", 0);
    if (wire_name(v.code).empty()) throw Refusal("bad_enum", 0);
    out += '{';
    out += '\n';
    pad(out, depth + 1);
    esc(out, "user");
    out += ": ";
    esc(out, std::string(wire_name(v.user)));
    out += ',';
    out += '\n';
    pad(out, depth + 1);
    esc(out, "process");
    out += ": ";
    esc(out, std::string(wire_name(v.process)));
    out += ',';
    out += '\n';
    pad(out, depth + 1);
    esc(out, "path");
    out += ": ";
    esc(out, std::string(wire_name(v.path)));
    out += ',';
    out += '\n';
    pad(out, depth + 1);
    esc(out, "package");
    out += ": ";
    esc(out, std::string(wire_name(v.package)));
    out += ',';
    out += '\n';
    pad(out, depth + 1);
    esc(out, "code");
    out += ": ";
    esc(out, std::string(wire_name(v.code)));
    out += '\n';
    pad(out, depth);
    out += '}';
}

inline void enc_proof_failure(std::string& out, const ProofFailure& v, int depth) {
    if (wire_name(v.have).empty()) throw Refusal("bad_enum", 0);
    if (wire_name(v.need).empty()) throw Refusal("bad_enum", 0);
    out += '{';
    out += '\n';
    pad(out, depth + 1);
    esc(out, "attribute");
    out += ": ";
    esc(out, v.attribute);
    out += ',';
    out += '\n';
    pad(out, depth + 1);
    esc(out, "have");
    out += ": ";
    esc(out, std::string(wire_name(v.have)));
    out += ',';
    out += '\n';
    pad(out, depth + 1);
    esc(out, "need");
    out += ": ";
    esc(out, std::string(wire_name(v.need)));
    out += ',';
    out += '\n';
    pad(out, depth + 1);
    esc(out, "why");
    out += ": ";
    esc(out, v.why);
    out += '\n';
    pad(out, depth);
    out += '}';
}

inline constexpr int kDepthLimit = 64;
inline constexpr std::size_t kI64Digits = 19;

inline void append_rune(std::string& out, std::uint32_t cp) {
    if (cp < 0x80) {
        out += static_cast<char>(cp);
    } else if (cp < 0x800) {
        out += static_cast<char>(0xC0 | (cp >> 6));
        out += static_cast<char>(0x80 | (cp & 0x3F));
    } else if (cp < 0x10000) {
        out += static_cast<char>(0xE0 | (cp >> 12));
        out += static_cast<char>(0x80 | ((cp >> 6) & 0x3F));
        out += static_cast<char>(0x80 | (cp & 0x3F));
    } else {
        out += static_cast<char>(0xF0 | (cp >> 18));
        out += static_cast<char>(0x80 | ((cp >> 12) & 0x3F));
        out += static_cast<char>(0x80 | ((cp >> 6) & 0x3F));
        out += static_cast<char>(0x80 | (cp & 0x3F));
    }
}

inline bool valid_utf8(const std::string& b) {
    for (std::size_t i = 0; i < b.size();) {
        const unsigned char c = static_cast<unsigned char>(b[i]);
        if (c < 0x80) { ++i; continue; }
        std::size_t n = 0;
        std::uint32_t cp = 0;
        if ((c >> 5) == 0x6) { n = 2; cp = c & 0x1Fu; }
        else if ((c >> 4) == 0xE) { n = 3; cp = c & 0x0Fu; }
        else if ((c >> 3) == 0x1E) { n = 4; cp = c & 0x07u; }
        else return false;
        if (i + n > b.size()) return false;
        for (std::size_t k = 1; k < n; ++k) {
            const unsigned char t = static_cast<unsigned char>(b[i + k]);
            if ((t >> 6) != 0x2) return false;
            cp = cp << 6 | (t & 0x3Fu);
        }
        static const std::uint32_t kLowest[5] = {0, 0, 0x80, 0x800, 0x10000};
        if (cp < kLowest[n] || cp > 0x10FFFF || (cp >= 0xD800 && cp <= 0xDFFF)) return false;
        i += n;
    }
    return true;
}

struct Reader {
    std::string_view buf;
    std::size_t pos = 0;
    int depth = 0;

    [[noreturn]] void refuse(const char* word) const { throw Refusal(word, pos); }

    unsigned char at() const {
        return pos < buf.size() ? static_cast<unsigned char>(buf[pos]) : 0;
    }

    bool digit() const { return at() >= '0' && at() <= '9'; }

    void skip_ws() {
        while (pos < buf.size() && ws(static_cast<unsigned char>(buf[pos]))) ++pos;
    }

    void enter() {
        if (++depth > kDepthLimit) refuse("depth_exceeded");
    }

    std::string str() {
        if (at() != '"') refuse("wrong_type");
        ++pos;
        std::string out;
        for (;;) {
            if (pos >= buf.size()) refuse("malformed");
            const unsigned char c = static_cast<unsigned char>(buf[pos]);
            if (c == '"') {
                ++pos;
                if (!valid_utf8(out)) refuse("bad_string");
                return out;
            }
            if (c < 0x20) refuse("bad_string");
            if (c == '\\') {
                escape(out);
            } else {
                out += static_cast<char>(c);
                ++pos;
            }
        }
    }

    void escape(std::string& out) {
        ++pos;
        if (pos >= buf.size()) refuse("malformed");
        const unsigned char c = static_cast<unsigned char>(buf[pos]);
        ++pos;
        switch (c) {
            case '"': case '\\': case '/': out += static_cast<char>(c); return;
            case 'b': out += static_cast<char>(0x08); return;
            case 'f': out += static_cast<char>(0x0c); return;
            case 'n': out += '\n'; return;
            case 'r': out += '\r'; return;
            case 't': out += '\t'; return;
            case 'u': break;
            default: refuse("bad_string");
        }
        std::uint32_t u = hex4();
        if (u >= 0xDC00 && u <= 0xDFFF) refuse("bad_string");
        if (u >= 0xD800 && u <= 0xDBFF) {
            if (pos + 1 >= buf.size() || buf[pos] != '\\' || buf[pos + 1] != 'u') refuse("bad_string");
            pos += 2;
            const std::uint32_t low = hex4();
            if (low < 0xDC00 || low > 0xDFFF) refuse("bad_string");
            u = 0x10000 + ((u - 0xD800) << 10) + (low - 0xDC00);
        }
        append_rune(out, u);
    }

    std::uint32_t hex4() {
        if (pos + 4 > buf.size()) refuse("bad_string");
        std::uint32_t u = 0;
        for (std::size_t i = 0; i < 4; ++i) {
            const unsigned char c = static_cast<unsigned char>(buf[pos + i]);
            if (c >= '0' && c <= '9') u = u << 4 | static_cast<std::uint32_t>(c - '0');
            else if (c >= 'a' && c <= 'f') u = u << 4 | static_cast<std::uint32_t>(c - 'a' + 10);
            else if (c >= 'A' && c <= 'F') u = u << 4 | static_cast<std::uint32_t>(c - 'A' + 10);
            else refuse("bad_string");
        }
        pos += 4;
        return u;
    }

    std::int64_t integer(std::int64_t low, std::int64_t high) {
        const unsigned char c = at();
        if (c != '-' && !digit()) refuse("wrong_type");
        const bool negative = c == '-';
        if (negative) ++pos;
        if (!digit()) refuse("malformed");
        std::uint64_t u = 0;
        if (at() == '0') {
            ++pos;
        } else {
            while (digit()) {
                if (u > 922337203685477580ULL) refuse("number_spelling");
                u = u * 10 + static_cast<std::uint64_t>(at() - '0');
                ++pos;
            }
        }
        const unsigned char after = at();
        if (after == '.' || after == 'e' || after == 'E' || digit()) refuse("number_spelling");
        if (negative && u == 0) refuse("number_spelling");
        std::int64_t n = 0;
        if (negative) {
            if (u > (1ULL << 63)) refuse("number_spelling");
            n = u == (1ULL << 63) ? INT64_MIN : -static_cast<std::int64_t>(u);
        } else {
            if (u > static_cast<std::uint64_t>(INT64_MAX)) refuse("number_spelling");
            n = static_cast<std::int64_t>(u);
        }
        if (n < low || n > high) refuse("number_spelling");
        return n;
    }

    bool boolean() {
        if (at() == 't') { literal("true"); return true; }
        if (at() == 'f') { literal("false"); return false; }
        refuse("wrong_type");
    }

    void literal(std::string_view word) {
        if (buf.substr(pos, word.size()) != word) refuse("malformed");
        pos += word.size();
    }

    std::vector<std::string> str_list() {
        if (at() != '[') refuse("wrong_type");
        enter();
        ++pos;
        std::vector<std::string> out;
        skip_ws();
        if (at() != ']') {
            for (;;) {
                skip_ws();
                out.push_back(str());
                skip_ws();
                if (at() != ',') break;
                ++pos;
            }
        }
        if (at() != ']') refuse("malformed");
        ++pos;
        --depth;
        return out;
    }

    std::map<std::string, Raw> raw_map() {
        if (at() != '{') refuse("wrong_type");
        enter();
        ++pos;
        std::map<std::string, Raw> out;
        skip_ws();
        if (at() != '}') {
            for (;;) {
                skip_ws();
                if (at() != '"') refuse("malformed");
                const std::string k = str();
                if (out.count(k) != 0) refuse("duplicate_key");
                skip_ws();
                if (at() != ':') refuse("malformed");
                ++pos;
                skip_ws();
                out[k] = raw_value();
                skip_ws();
                if (at() != ',') break;
                ++pos;
            }
        }
        if (at() != '}') refuse("malformed");
        ++pos;
        --depth;
        return out;
    }

    Raw raw_value() {
        const std::size_t start = pos;
        skip_value();
        return std::string(buf.substr(start, pos - start));
    }

    void skip_value() {
        const unsigned char c = at();
        if (c == '"') skip_string();
        else if (c == '{' || c == '[') skip_container();
        else if (c == 't') literal("true");
        else if (c == 'f') literal("false");
        else if (c == 'n') literal("null");
        else if (c == '-' || digit()) skip_number();
        else refuse("malformed");
    }

    // An opaque value is validated and carried, never interpreted. Its syntax is
    // the record's own — the same string reader, so an escape, a control byte or
    // a lone surrogate is judged identically at any depth — and what it is free
    // to spell, it keeps: the bytes between these two offsets are what a writer
    // re-emits. A number is walked, never converted, so a value no host type
    // holds survives the reader that carried it.
    void skip_string() { str(); }

    void some_digits() {
        int n = 0;
        while (digit()) { ++pos; ++n; }
        if (n == 0) refuse("number_spelling");
    }

    void skip_number() {
        if (at() == '-') ++pos;
        const unsigned char c = at();
        if (c == '0') ++pos;
        else if (c >= '1' && c <= '9') { while (digit()) ++pos; }
        else refuse("number_spelling");
        if (at() == '.') { ++pos; some_digits(); }
        if (at() == 'e' || at() == 'E') {
            ++pos;
            if (at() == '+' || at() == '-') ++pos;
            some_digits();
        }
    }

    void skip_container() {
        const unsigned char opener = at();
        const char shut = opener == '{' ? '}' : ']';
        enter();
        ++pos;
        skip_ws();
        std::map<std::string, bool> seen;
        if (at() != static_cast<unsigned char>(shut)) {
            for (;;) {
                skip_ws();
                if (opener == '{') {
                    if (at() != '"') refuse("malformed");
                    const std::string k = str();
                    if (!seen.emplace(k, true).second) refuse("duplicate_key");
                    skip_ws();
                    if (at() != ':') refuse("malformed");
                    ++pos;
                    skip_ws();
                }
                skip_value();
                skip_ws();
                if (at() != ',') break;
                ++pos;
            }
        }
        if (at() != static_cast<unsigned char>(shut)) refuse("malformed");
        ++pos;
        --depth;
    }
};

inline ProofRequirement decode_proof_requirement(Reader& r);
inline ProofFailure decode_proof_failure(Reader& r);

inline ProofRequirement decode_proof_requirement(Reader& r) {
    if (r.at() != '{') r.refuse("wrong_type");
    r.enter();
    ++r.pos;
    ProofRequirement v;
    std::optional<std::string> wire_user;
    std::optional<std::string> wire_process;
    std::optional<std::string> wire_path;
    std::optional<std::string> wire_package;
    std::optional<std::string> wire_code;
    std::uint32_t seen = 0;
    r.skip_ws();
    if (r.at() != '}') {
        for (;;) {
            r.skip_ws();
            if (r.at() != '"') r.refuse("malformed");
            const std::string key = r.str();
            r.skip_ws();
            if (r.at() != ':') r.refuse("malformed");
            ++r.pos;
            r.skip_ws();
            if (key == "user") {
                if (seen & 1u) r.refuse("duplicate_field");
                seen |= 1u;
                wire_user = r.str();
            } else if (key == "process") {
                if (seen & 2u) r.refuse("duplicate_field");
                seen |= 2u;
                wire_process = r.str();
            } else if (key == "path") {
                if (seen & 4u) r.refuse("duplicate_field");
                seen |= 4u;
                wire_path = r.str();
            } else if (key == "package") {
                if (seen & 8u) r.refuse("duplicate_field");
                seen |= 8u;
                wire_package = r.str();
            } else if (key == "code") {
                if (seen & 16u) r.refuse("duplicate_field");
                seen |= 16u;
                wire_code = r.str();
            } else {
                r.refuse("unknown_field");
            }
            r.skip_ws();
            if (r.at() != ',') break;
            ++r.pos;
        }
    }
    if (r.at() != '}') r.refuse("malformed");
    ++r.pos;
    --r.depth;
    if ((seen & 31u) != 31u) r.refuse("missing_field");
    if (wire_user) {
        const auto parsed = parse_proof(*wire_user);
        if (!parsed) r.refuse("bad_enum");
        v.user = *parsed;
    }
    if (wire_process) {
        const auto parsed = parse_proof(*wire_process);
        if (!parsed) r.refuse("bad_enum");
        v.process = *parsed;
    }
    if (wire_path) {
        const auto parsed = parse_proof(*wire_path);
        if (!parsed) r.refuse("bad_enum");
        v.path = *parsed;
    }
    if (wire_package) {
        const auto parsed = parse_proof(*wire_package);
        if (!parsed) r.refuse("bad_enum");
        v.package = *parsed;
    }
    if (wire_code) {
        const auto parsed = parse_proof(*wire_code);
        if (!parsed) r.refuse("bad_enum");
        v.code = *parsed;
    }
    return v;
}

inline ProofFailure decode_proof_failure(Reader& r) {
    if (r.at() != '{') r.refuse("wrong_type");
    r.enter();
    ++r.pos;
    ProofFailure v;
    std::optional<std::string> wire_have;
    std::optional<std::string> wire_need;
    std::uint32_t seen = 0;
    r.skip_ws();
    if (r.at() != '}') {
        for (;;) {
            r.skip_ws();
            if (r.at() != '"') r.refuse("malformed");
            const std::string key = r.str();
            r.skip_ws();
            if (r.at() != ':') r.refuse("malformed");
            ++r.pos;
            r.skip_ws();
            if (key == "attribute") {
                if (seen & 1u) r.refuse("duplicate_field");
                seen |= 1u;
                v.attribute = r.str();
            } else if (key == "have") {
                if (seen & 2u) r.refuse("duplicate_field");
                seen |= 2u;
                wire_have = r.str();
            } else if (key == "need") {
                if (seen & 4u) r.refuse("duplicate_field");
                seen |= 4u;
                wire_need = r.str();
            } else if (key == "why") {
                if (seen & 8u) r.refuse("duplicate_field");
                seen |= 8u;
                v.why = r.str();
            } else {
                r.refuse("unknown_field");
            }
            r.skip_ws();
            if (r.at() != ',') break;
            ++r.pos;
        }
    }
    if (r.at() != '}') r.refuse("malformed");
    ++r.pos;
    --r.depth;
    if ((seen & 15u) != 15u) r.refuse("missing_field");
    if (wire_have) {
        const auto parsed = parse_proof(*wire_have);
        if (!parsed) r.refuse("bad_enum");
        v.have = *parsed;
    }
    if (wire_need) {
        const auto parsed = parse_proof(*wire_need);
        if (!parsed) r.refuse("bad_enum");
        v.need = *parsed;
    }
    return v;
}

}  // namespace detail

inline std::string encode(const ProofRequirement& v) {
    std::string out;
    detail::enc_proof_requirement(out, v, 0);
    out += '\n';
    return out;
}

inline ProofRequirement decode(std::string_view data) {
    detail::Reader r{data};
    r.skip_ws();
    ProofRequirement v = detail::decode_proof_requirement(r);
    r.skip_ws();
    if (r.pos < r.buf.size()) r.refuse("trailing_bytes");
    return v;
}

namespace detail {
// kRefusals is in the order two of them are chosen between.
inline const std::vector<std::string> kRefusals = {"malformed", "bad_string", "number_spelling", "wrong_type", "depth_exceeded", "duplicate_key", "duplicate_field", "unknown_field", "missing_field", "bad_enum", "trailing_bytes"};

inline int refusal_rank(std::string_view word) {
    for (std::size_t i = 0; i < kRefusals.size(); ++i)
        if (kRefusals[i] == word) return static_cast<int>(i);
    return -1;
}
}  // namespace detail

}  // namespace abstraction::identity::api
