// Code generated by abstraction-idl from abstraction-identity/identity.thrift. DO NOT EDIT.

package api

type Raw = string

func escByte(out []byte, c byte) []byte {
	const hex = "0123456789abcdef"
	switch c {
	case '"':
		return append(out, '\\', '"')
	case '\\':
		return append(out, '\\', '\\')
	case 0x08:
		return append(out, '\\', 'b')
	case 0x0c:
		return append(out, '\\', 'f')
	case '\n':
		return append(out, '\\', 'n')
	case '\r':
		return append(out, '\\', 'r')
	case '\t':
		return append(out, '\\', 't')
	}
	if c < 0x20 {
		return append(out, '\\', 'u', '0', '0', hex[c>>4], hex[c&0xF])
	}
	return append(out, c)
}

func num(out []byte, n int64) []byte {
	if n == 0 {
		return append(out, '0')
	}
	var d [24]byte
	p := len(d)
	u := uint64(n)
	if n < 0 {
		u = -uint64(n)
	}
	for u > 0 {
		p--
		d[p] = byte('0' + u%10)
		u /= 10
	}
	if n < 0 {
		out = append(out, '-')
	}
	return append(out, d[p:]...)
}

func pad(out []byte, depth int) []byte {
	for i := 0; i < depth*2; i++ {
		out = append(out, ' ')
	}
	return out
}

func strs(out []byte, v []string, depth int) []byte {
	if len(v) == 0 {
		return append(out, '[', ']')
	}
	out = append(out, '[', '\n')
	for i, s := range v {
		out = pad(out, depth+1)
		out = esc(out, s)
		if i+1 < len(v) {
			out = append(out, ',')
		}
		out = append(out, '\n')
	}
	out = pad(out, depth)
	return append(out, ']')
}

func raw(out []byte, s string, depth int) []byte {
	ws := func(c byte) bool { return c == ' ' || c == '\t' || c == '\n' || c == '\r' }
	for i := 0; i < len(s); {
		c := s[i]
		if ws(c) {
			i++
			continue
		}
		switch c {
		case '"':
			j := i + 1
			for j < len(s) {
				if s[j] == '\\' {
					j += 2
					continue
				}
				if s[j] == '"' {
					j++
					break
				}
				j++
			}
			out = append(out, s[i:j]...)
			i = j
		case '{', '[':
			out = append(out, c)
			i++
			j := i
			for j < len(s) && ws(s[j]) {
				j++
			}
			if j < len(s) && (s[j] == '}' || s[j] == ']') {
				out = append(out, s[j])
				i = j + 1
			} else {
				depth++
				out = append(out, '\n')
				out = pad(out, depth)
			}
		case '}', ']':
			depth--
			out = append(out, '\n')
			out = pad(out, depth)
			out = append(out, c)
			i++
		case ',':
			out = append(out, ',', '\n')
			out = pad(out, depth)
			i++
		case ':':
			out = append(out, ':', ' ')
			i++
		default:
			out = append(out, c)
			i++
		}
	}
	return out
}

func byteLess(a, b string) bool {
	n := len(a)
	if len(b) < n {
		n = len(b)
	}
	for i := 0; i < n; i++ {
		if a[i] != b[i] {
			return a[i] < b[i]
		}
	}
	return len(a) < len(b)
}

func sortedKeys(m map[string]Raw) []string {
	keys := make([]string, 0, len(m))
	for k := range m {
		keys = append(keys, k)
	}
	for i := 1; i < len(keys); i++ {
		for j := i; j > 0 && byteLess(keys[j], keys[j-1]); j-- {
			keys[j], keys[j-1] = keys[j-1], keys[j]
		}
	}
	return keys
}

func rawmap(out []byte, m map[string]Raw, depth int) []byte {
	keys := sortedKeys(m)
	if len(keys) == 0 {
		return append(out, '{', '}')
	}
	out = append(out, '{', '\n')
	for i, k := range keys {
		out = pad(out, depth+1)
		out = esc(out, k)
		out = append(out, ':', ' ')
		out = raw(out, m[k], depth+1)
		if i+1 < len(keys) {
			out = append(out, ',')
		}
		out = append(out, '\n')
	}
	out = pad(out, depth)
	return append(out, '}')
}

func esc(out []byte, s string) []byte {
	out = append(out, '"')
	for i := 0; i < len(s); i++ {
		out = escByte(out, s[i])
	}
	return append(out, '"')
}

// Proof is a closed vocabulary. Its numeric values are private implementation
// tags; String and ParseProof preserve the exact wire words.
type Proof uint32

const (
	ProofNone     Proof = 1
	ProofClaimed  Proof = 2
	ProofInvalid  Proof = 3
	ProofUnsigned Proof = 4
	ProofUnmet    Proof = 5
	ProofPID      Proof = 6
	ProofBound    Proof = 7
	ProofKernel   Proof = 8
	ProofSigned   Proof = 9
)

// String returns v's exact wire word, or the empty string for an invalid value.
func (v Proof) String() string {
	word, _ := v.WireName()
	return word
}

// WireName returns v's exact wire word and whether v names a member.
func (v Proof) WireName() (string, bool) {
	switch v {
	case ProofNone:
		return "none", true
	case ProofClaimed:
		return "claimed", true
	case ProofInvalid:
		return "invalid", true
	case ProofUnsigned:
		return "unsigned", true
	case ProofUnmet:
		return "unmet", true
	case ProofPID:
		return "pid", true
	case ProofBound:
		return "bound", true
	case ProofKernel:
		return "kernel", true
	case ProofSigned:
		return "signed", true
	}
	return "", false
}

// ParseProof returns the member named by an exact wire word.
func ParseProof(word string) (Proof, bool) {
	switch word {
	case "none":
		return ProofNone, true
	case "claimed":
		return ProofClaimed, true
	case "invalid":
		return ProofInvalid, true
	case "unsigned":
		return ProofUnsigned, true
	case "unmet":
		return ProofUnmet, true
	case "pid":
		return ProofPID, true
	case "bound":
		return ProofBound, true
	case "kernel":
		return ProofKernel, true
	case "signed":
		return ProofSigned, true
	}
	return Proof(0), false
}

// MarshalText preserves the member's exact wire word for standard text users,
// including JSON object keys. Invalid and zero values are refused.
func (v Proof) MarshalText() ([]byte, error) {
	word, ok := v.WireName()
	if !ok {
		return nil, &Refusal{Word: "bad_enum", Offset: 0}
	}
	return []byte(word), nil
}

// UnmarshalText accepts an exact wire word and refuses unknown text.
func (v *Proof) UnmarshalText(text []byte) error {
	word, ok := ParseProof(string(text))
	if !ok {
		return &Refusal{Word: "bad_enum", Offset: 0}
	}
	*v = word
	return nil
}

// MarshalJSON keeps closed vocabularies as JSON strings rather than their
// private numeric implementation tags.
func (v Proof) MarshalJSON() ([]byte, error) {
	word, ok := v.WireName()
	if !ok {
		return nil, &Refusal{Word: "bad_enum", Offset: 0}
	}
	return esc(nil, word), nil
}

// UnmarshalJSON accepts only an exact JSON string member. Numbers, null and
// unknown strings are refused by the same codec rules as generated records.
func (v *Proof) UnmarshalJSON(data []byte) error {
	r := reader{buf: data}
	r.ws()
	word, err := r.str()
	if err != nil {
		return err
	}
	r.ws()
	if r.pos != len(r.buf) {
		return r.refuse("trailing_bytes")
	}
	parsed, ok := ParseProof(word)
	if !ok {
		return r.refuse("bad_enum")
	}
	*v = parsed
	return nil
}

// ProofValues returns every member of Proof in declaration order, in a new slice.
func ProofValues() []Proof {
	return []Proof{ProofNone, ProofClaimed, ProofInvalid, ProofUnsigned, ProofUnmet, ProofPID, ProofBound, ProofKernel, ProofSigned}
}

// Known reports whether v is a member of Proof.
func (v Proof) Known() bool {
	_, ok := v.WireName()
	return ok
}

var NativeOperations = []string{"OfHandle", "OfConn", "CanEver", "Check", "Get", "AtLeast"}

var NativeBindingTypes = []string{"Handle", "Peer", "Attr<T>", "User", "Process", "Code", "Options"}

// Minimum proof for each native Peer attribute. Policy comparison uses the
// declared native order. A serialized requirement or proof name never supplies
// caller identity; native bindings derive values from the accepted connection.
type ProofRequirement struct {
	User    Proof
	Process Proof
	Path    Proof
	Package Proof
	Code    Proof
}

// Diagnostic refusal metadata. Underlying native attribute and connection
// evidence remain inseparable; this record cannot create authenticated
// evidence.
type ProofFailure struct {
	Attribute string
	Have      Proof
	Need      Proof
	Why       string
}

func encProofRequirement(out []byte, v *ProofRequirement, depth int) []byte {
	if !(v.User).Known() {
		panic(&Refusal{Word: "bad_enum", Offset: 0})
	}
	if !(v.Process).Known() {
		panic(&Refusal{Word: "bad_enum", Offset: 0})
	}
	if !(v.Path).Known() {
		panic(&Refusal{Word: "bad_enum", Offset: 0})
	}
	if !(v.Package).Known() {
		panic(&Refusal{Word: "bad_enum", Offset: 0})
	}
	if !(v.Code).Known() {
		panic(&Refusal{Word: "bad_enum", Offset: 0})
	}
	out = append(out, '{')
	out = append(out, '\n')
	out = pad(out, depth+1)
	out = esc(out, "user")
	out = append(out, ':', ' ')
	out = esc(out, v.User.String())
	out = append(out, ',')
	out = append(out, '\n')
	out = pad(out, depth+1)
	out = esc(out, "process")
	out = append(out, ':', ' ')
	out = esc(out, v.Process.String())
	out = append(out, ',')
	out = append(out, '\n')
	out = pad(out, depth+1)
	out = esc(out, "path")
	out = append(out, ':', ' ')
	out = esc(out, v.Path.String())
	out = append(out, ',')
	out = append(out, '\n')
	out = pad(out, depth+1)
	out = esc(out, "package")
	out = append(out, ':', ' ')
	out = esc(out, v.Package.String())
	out = append(out, ',')
	out = append(out, '\n')
	out = pad(out, depth+1)
	out = esc(out, "code")
	out = append(out, ':', ' ')
	out = esc(out, v.Code.String())
	out = append(out, '\n')
	out = pad(out, depth)
	return append(out, '}')
}

func encProofFailure(out []byte, v *ProofFailure, depth int) []byte {
	if !(v.Have).Known() {
		panic(&Refusal{Word: "bad_enum", Offset: 0})
	}
	if !(v.Need).Known() {
		panic(&Refusal{Word: "bad_enum", Offset: 0})
	}
	out = append(out, '{')
	out = append(out, '\n')
	out = pad(out, depth+1)
	out = esc(out, "attribute")
	out = append(out, ':', ' ')
	out = esc(out, v.Attribute)
	out = append(out, ',')
	out = append(out, '\n')
	out = pad(out, depth+1)
	out = esc(out, "have")
	out = append(out, ':', ' ')
	out = esc(out, v.Have.String())
	out = append(out, ',')
	out = append(out, '\n')
	out = pad(out, depth+1)
	out = esc(out, "need")
	out = append(out, ':', ' ')
	out = esc(out, v.Need.String())
	out = append(out, ',')
	out = append(out, '\n')
	out = pad(out, depth+1)
	out = esc(out, "why")
	out = append(out, ':', ' ')
	out = esc(out, v.Why)
	out = append(out, '\n')
	out = pad(out, depth)
	return append(out, '}')
}

func Encode(v *ProofRequirement) []byte {
	return append(encProofRequirement(nil, v, 0), '\n')
}

type Refusal struct {
	Word   string
	Offset int
}

func (r *Refusal) Error() string {
	return "refused: " + r.Word + " at byte " + decimal(int64(r.Offset))
}

func decimal(n int64) string { return string(num(nil, n)) }

const depthLimit = 64

type reader struct {
	buf   []byte
	pos   int
	depth int
}

func (r *reader) refuse(word string) error { return &Refusal{Word: word, Offset: r.pos} }

func (r *reader) at() byte {
	if r.pos < len(r.buf) {
		return r.buf[r.pos]
	}
	return 0
}

func (r *reader) ws() {
	for r.pos < len(r.buf) {
		switch r.buf[r.pos] {
		case ' ', '\t', '\n', '\r':
			r.pos++
		default:
			return
		}
	}
}

func (r *reader) enter() error {
	r.depth++
	if r.depth > depthLimit {
		return r.refuse("depth_exceeded")
	}
	return nil
}

func (r *reader) str() (string, error) {
	if r.at() != '"' {
		return "", r.refuse("wrong_type")
	}
	r.pos++
	var out []byte
	for {
		if r.pos >= len(r.buf) {
			return "", r.refuse("malformed")
		}
		c := r.buf[r.pos]
		switch {
		case c == '"':
			r.pos++
			if !validUTF8(out) {
				return "", r.refuse("bad_string")
			}
			return string(out), nil
		case c < 0x20:
			return "", r.refuse("bad_string")
		case c == '\\':
			var err error
			if out, err = r.escape(out); err != nil {
				return "", err
			}
		default:
			out = append(out, c)
			r.pos++
		}
	}
}

func (r *reader) escape(out []byte) ([]byte, error) {
	r.pos++
	if r.pos >= len(r.buf) {
		return nil, r.refuse("malformed")
	}
	c := r.buf[r.pos]
	r.pos++
	switch c {
	case '"', '\\', '/':
		return append(out, c), nil
	case 'b':
		return append(out, 0x08), nil
	case 'f':
		return append(out, 0x0c), nil
	case 'n':
		return append(out, '\n'), nil
	case 'r':
		return append(out, '\r'), nil
	case 't':
		return append(out, '\t'), nil
	case 'u':
		u, err := r.hex4()
		if err != nil {
			return nil, err
		}
		if u >= 0xDC00 && u <= 0xDFFF {
			return nil, r.refuse("bad_string")
		}
		if u >= 0xD800 && u <= 0xDBFF {
			if r.pos+1 >= len(r.buf) || r.buf[r.pos] != '\\' || r.buf[r.pos+1] != 'u' {
				return nil, r.refuse("bad_string")
			}
			r.pos += 2
			lo, err := r.hex4()
			if err != nil {
				return nil, err
			}
			if lo < 0xDC00 || lo > 0xDFFF {
				return nil, r.refuse("bad_string")
			}
			u = 0x10000 + (u-0xD800)<<10 + (lo - 0xDC00)
		}
		return appendRune(out, u), nil
	}
	return nil, r.refuse("bad_string")
}

func (r *reader) hex4() (int32, error) {
	if r.pos+4 > len(r.buf) {
		return 0, r.refuse("bad_string")
	}
	var u int32
	for i := 0; i < 4; i++ {
		c := r.buf[r.pos+i]
		switch {
		case c >= '0' && c <= '9':
			u = u<<4 | int32(c-'0')
		case c >= 'a' && c <= 'f':
			u = u<<4 | int32(c-'a'+10)
		case c >= 'A' && c <= 'F':
			u = u<<4 | int32(c-'A'+10)
		default:
			return 0, r.refuse("bad_string")
		}
	}
	r.pos += 4
	return u, nil
}

func appendRune(out []byte, cp int32) []byte {
	switch {
	case cp < 0x80:
		return append(out, byte(cp))
	case cp < 0x800:
		return append(out, byte(0xC0|cp>>6), byte(0x80|cp&0x3F))
	case cp < 0x10000:
		return append(out, byte(0xE0|cp>>12), byte(0x80|cp>>6&0x3F), byte(0x80|cp&0x3F))
	}
	return append(out, byte(0xF0|cp>>18), byte(0x80|cp>>12&0x3F), byte(0x80|cp>>6&0x3F), byte(0x80|cp&0x3F))
}

func validUTF8(b []byte) bool {
	for i := 0; i < len(b); {
		c := b[i]
		var n int
		var cp int32
		switch {
		case c < 0x80:
			i++
			continue
		case c>>5 == 0x6:
			n, cp = 2, int32(c&0x1F)
		case c>>4 == 0xE:
			n, cp = 3, int32(c&0x0F)
		case c>>3 == 0x1E:
			n, cp = 4, int32(c&0x07)
		default:
			return false
		}
		if i+n > len(b) {
			return false
		}
		for k := 1; k < n; k++ {
			if b[i+k]>>6 != 0x2 {
				return false
			}
			cp = cp<<6 | int32(b[i+k]&0x3F)
		}
		lowest := []int32{0, 0, 0x80, 0x800, 0x10000}[n]
		if cp < lowest || cp > 0x10FFFF || (cp >= 0xD800 && cp <= 0xDFFF) {
			return false
		}
		i += n
	}
	return true
}

func (r *reader) integer(min, max int64) (int64, error) {
	c := r.at()
	if c != '-' && (c < '0' || c > '9') {
		return 0, r.refuse("wrong_type")
	}
	neg := c == '-'
	if neg {
		r.pos++
	}
	d := r.at()
	if d < '0' || d > '9' {
		return 0, r.refuse("malformed")
	}
	var u uint64
	if d == '0' {
		r.pos++
	} else {
		for d = r.at(); d >= '0' && d <= '9'; d = r.at() {
			if u > 922337203685477580 {
				return 0, r.refuse("number_spelling")
			}
			u = u*10 + uint64(d-'0')
			r.pos++
		}
	}
	switch c := r.at(); {
	case c == '.' || c == 'e' || c == 'E' || (c >= '0' && c <= '9'):
		return 0, r.refuse("number_spelling")
	}
	if neg && u == 0 {
		return 0, r.refuse("number_spelling")
	}
	var n int64
	switch {
	case neg && u == 1<<63:
		n = -1 << 63
	case u > 1<<63-1:
		return 0, r.refuse("number_spelling")
	case neg:
		n = -int64(u)
	default:
		n = int64(u)
	}
	if n < min || n > max {
		return 0, r.refuse("number_spelling")
	}
	return n, nil
}

func (r *reader) boolean() (bool, error) {
	switch r.at() {
	case 't':
		return true, r.literal("true")
	case 'f':
		return false, r.literal("false")
	}
	return false, r.refuse("wrong_type")
}

func (r *reader) literal(word string) error {
	if r.pos+len(word) > len(r.buf) || string(r.buf[r.pos:r.pos+len(word)]) != word {
		return r.refuse("malformed")
	}
	r.pos += len(word)
	return nil
}

func (r *reader) strList() ([]string, error) {
	if r.at() != '[' {
		return nil, r.refuse("wrong_type")
	}
	if err := r.enter(); err != nil {
		return nil, err
	}
	r.pos++
	out := []string{}
	r.ws()
	if r.at() != ']' {
		for {
			r.ws()
			s, err := r.str()
			if err != nil {
				return nil, err
			}
			out = append(out, s)
			r.ws()
			if r.at() != ',' {
				break
			}
			r.pos++
		}
	}
	if r.at() != ']' {
		return nil, r.refuse("malformed")
	}
	r.pos++
	r.depth--
	return out, nil
}

func (r *reader) rawMap() (map[string]Raw, error) {
	if r.at() != '{' {
		return nil, r.refuse("wrong_type")
	}
	if err := r.enter(); err != nil {
		return nil, err
	}
	r.pos++
	out := map[string]Raw{}
	r.ws()
	if r.at() != '}' {
		for {
			r.ws()
			if r.at() != '"' {
				return nil, r.refuse("malformed")
			}
			k, err := r.str()
			if err != nil {
				return nil, err
			}
			if _, again := out[k]; again {
				return nil, r.refuse("duplicate_key")
			}
			r.ws()
			if r.at() != ':' {
				return nil, r.refuse("malformed")
			}
			r.pos++
			r.ws()
			v, err := r.rawValue()
			if err != nil {
				return nil, err
			}
			out[k] = v
			r.ws()
			if r.at() != ',' {
				break
			}
			r.pos++
		}
	}
	if r.at() != '}' {
		return nil, r.refuse("malformed")
	}
	r.pos++
	r.depth--
	return out, nil
}

func (r *reader) rawValue() (Raw, error) {
	start := r.pos
	if err := r.skipValue(); err != nil {
		return "", err
	}
	return Raw(r.buf[start:r.pos]), nil
}

func (r *reader) skipValue() error {
	c := r.at()
	switch {
	case c == '"':
		return r.skipString()
	case c == '{' || c == '[':
		return r.skipContainer()
	case c == 't':
		return r.literal("true")
	case c == 'f':
		return r.literal("false")
	case c == 'n':
		return r.literal("null")
	case c == '-' || (c >= '0' && c <= '9'):
		return r.skipNumber()
	}
	return r.refuse("malformed")
}

// An opaque value is validated and carried, never interpreted. Its syntax is
// the record's own — the same string reader, so an escape, a control byte or a
// lone surrogate is judged identically at any depth — and what it is free to
// spell, it keeps: the bytes between these two offsets are what a writer
// re-emits. A number is walked, never converted, so a value no host type holds
// survives the reader that carried it.
func (r *reader) skipString() error {
	_, err := r.str()
	return err
}

func (r *reader) skipNumber() error {
	if r.at() == '-' {
		r.pos++
	}
	switch c := r.at(); {
	case c == '0':
		r.pos++
	case c >= '1' && c <= '9':
		for c := r.at(); c >= '0' && c <= '9'; c = r.at() {
			r.pos++
		}
	default:
		return r.refuse("number_spelling")
	}
	if r.at() == '.' {
		r.pos++
		if err := r.someDigits(); err != nil {
			return err
		}
	}
	if c := r.at(); c == 'e' || c == 'E' {
		r.pos++
		if c := r.at(); c == '+' || c == '-' {
			r.pos++
		}
		if err := r.someDigits(); err != nil {
			return err
		}
	}
	return nil
}

func (r *reader) someDigits() error {
	n := 0
	for c := r.at(); c >= '0' && c <= '9'; c = r.at() {
		r.pos++
		n++
	}
	if n == 0 {
		return r.refuse("number_spelling")
	}
	return nil
}

func (r *reader) skipContainer() error {
	open := r.buf[r.pos]
	shut := byte('}')
	if open == '[' {
		shut = ']'
	}
	if err := r.enter(); err != nil {
		return err
	}
	r.pos++
	r.ws()
	seen := map[string]bool{}
	if r.at() != shut {
		for {
			r.ws()
			if open == '{' {
				if r.at() != '"' {
					return r.refuse("malformed")
				}
				k, err := r.str()
				if err != nil {
					return err
				}
				if seen[k] {
					return r.refuse("duplicate_key")
				}
				seen[k] = true
				r.ws()
				if r.at() != ':' {
					return r.refuse("malformed")
				}
				r.pos++
				r.ws()
			}
			if err := r.skipValue(); err != nil {
				return err
			}
			r.ws()
			if r.at() != ',' {
				break
			}
			r.pos++
		}
	}
	if r.at() != shut {
		return r.refuse("malformed")
	}
	r.pos++
	r.depth--
	return nil
}

func (r *reader) decodeProofRequirement() (*ProofRequirement, error) {
	if r.at() != '{' {
		return nil, r.refuse("wrong_type")
	}
	if err := r.enter(); err != nil {
		return nil, err
	}
	r.pos++
	v := &ProofRequirement{}
	var seen uint32
	r.ws()
	if r.at() != '}' {
		for {
			r.ws()
			if r.at() != '"' {
				return nil, r.refuse("malformed")
			}
			key, err := r.str()
			if err != nil {
				return nil, err
			}
			r.ws()
			if r.at() != ':' {
				return nil, r.refuse("malformed")
			}
			r.pos++
			r.ws()
			switch key {
			case "user":
				if seen&1 != 0 {
					return nil, r.refuse("duplicate_field")
				}
				seen |= 1
				x, err := r.str()
				if err != nil {
					return nil, err
				}
				word, ok := ParseProof(x)
				if !ok {
					return nil, r.refuse("bad_enum")
				}
				v.User = word
			case "process":
				if seen&2 != 0 {
					return nil, r.refuse("duplicate_field")
				}
				seen |= 2
				x, err := r.str()
				if err != nil {
					return nil, err
				}
				word, ok := ParseProof(x)
				if !ok {
					return nil, r.refuse("bad_enum")
				}
				v.Process = word
			case "path":
				if seen&4 != 0 {
					return nil, r.refuse("duplicate_field")
				}
				seen |= 4
				x, err := r.str()
				if err != nil {
					return nil, err
				}
				word, ok := ParseProof(x)
				if !ok {
					return nil, r.refuse("bad_enum")
				}
				v.Path = word
			case "package":
				if seen&8 != 0 {
					return nil, r.refuse("duplicate_field")
				}
				seen |= 8
				x, err := r.str()
				if err != nil {
					return nil, err
				}
				word, ok := ParseProof(x)
				if !ok {
					return nil, r.refuse("bad_enum")
				}
				v.Package = word
			case "code":
				if seen&16 != 0 {
					return nil, r.refuse("duplicate_field")
				}
				seen |= 16
				x, err := r.str()
				if err != nil {
					return nil, err
				}
				word, ok := ParseProof(x)
				if !ok {
					return nil, r.refuse("bad_enum")
				}
				v.Code = word
			default:
				return nil, r.refuse("unknown_field")
			}
			r.ws()
			if r.at() != ',' {
				break
			}
			r.pos++
		}
	}
	if r.at() != '}' {
		return nil, r.refuse("malformed")
	}
	r.pos++
	r.depth--
	if seen&31 != 31 {
		return nil, r.refuse("missing_field")
	}
	if !(v.User).Known() {
		return nil, r.refuse("bad_enum")
	}
	if !(v.Process).Known() {
		return nil, r.refuse("bad_enum")
	}
	if !(v.Path).Known() {
		return nil, r.refuse("bad_enum")
	}
	if !(v.Package).Known() {
		return nil, r.refuse("bad_enum")
	}
	if !(v.Code).Known() {
		return nil, r.refuse("bad_enum")
	}
	return v, nil
}

func (r *reader) decodeProofFailure() (*ProofFailure, error) {
	if r.at() != '{' {
		return nil, r.refuse("wrong_type")
	}
	if err := r.enter(); err != nil {
		return nil, err
	}
	r.pos++
	v := &ProofFailure{}
	var seen uint32
	r.ws()
	if r.at() != '}' {
		for {
			r.ws()
			if r.at() != '"' {
				return nil, r.refuse("malformed")
			}
			key, err := r.str()
			if err != nil {
				return nil, err
			}
			r.ws()
			if r.at() != ':' {
				return nil, r.refuse("malformed")
			}
			r.pos++
			r.ws()
			switch key {
			case "attribute":
				if seen&1 != 0 {
					return nil, r.refuse("duplicate_field")
				}
				seen |= 1
				x, err := r.str()
				if err != nil {
					return nil, err
				}
				v.Attribute = x
			case "have":
				if seen&2 != 0 {
					return nil, r.refuse("duplicate_field")
				}
				seen |= 2
				x, err := r.str()
				if err != nil {
					return nil, err
				}
				word, ok := ParseProof(x)
				if !ok {
					return nil, r.refuse("bad_enum")
				}
				v.Have = word
			case "need":
				if seen&4 != 0 {
					return nil, r.refuse("duplicate_field")
				}
				seen |= 4
				x, err := r.str()
				if err != nil {
					return nil, err
				}
				word, ok := ParseProof(x)
				if !ok {
					return nil, r.refuse("bad_enum")
				}
				v.Need = word
			case "why":
				if seen&8 != 0 {
					return nil, r.refuse("duplicate_field")
				}
				seen |= 8
				x, err := r.str()
				if err != nil {
					return nil, err
				}
				v.Why = x
			default:
				return nil, r.refuse("unknown_field")
			}
			r.ws()
			if r.at() != ',' {
				break
			}
			r.pos++
		}
	}
	if r.at() != '}' {
		return nil, r.refuse("malformed")
	}
	r.pos++
	r.depth--
	if seen&15 != 15 {
		return nil, r.refuse("missing_field")
	}
	if !(v.Have).Known() {
		return nil, r.refuse("bad_enum")
	}
	if !(v.Need).Known() {
		return nil, r.refuse("bad_enum")
	}
	return v, nil
}

func Decode(in []byte) (*ProofRequirement, error) {
	r := &reader{buf: in}
	r.ws()
	v, err := r.decodeProofRequirement()
	if err != nil {
		return nil, err
	}
	r.ws()
	if r.pos < len(r.buf) {
		return nil, r.refuse("trailing_bytes")
	}
	return v, nil
}

// refusals is in the order two of them are chosen between.

var refusals = []string{"malformed", "bad_string", "number_spelling", "wrong_type", "depth_exceeded", "duplicate_key", "duplicate_field", "unknown_field", "missing_field", "bad_enum", "trailing_bytes"}

func refusalRank(word string) int {
	for i, w := range refusals {
		if w == word {
			return i
		}
	}
	return -1
}
